---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: James
spec:
  memberOf: [guests]
  profile:
    email: james.leach1999@gmail.com
    displayName: JamesLeach1999
